---
- hosts: all
  tasks:
    - name: Update repositories cache and install "openjdk-8-jdk-headless" package
      become: true
      apt:
        name: openjdk-8-jdk-headless
        update_cache: yes
    - name: Create SSH folder
      file:
        path: /home/vagrant/.ssh
        state: directory
        mode: 0700
    - name: Get vagrant insecure keys
      get_url:
        url: https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
        dest: /home/vagrant/.ssh/authorized_keys
        mode: 0600
    - name: Mount Guest additions
      become: true
      mount:
        name: /mnt
        src: /home/vagrant/VBoxGuestAdditions.iso
        opts: loop,ro
        state: mounted
        fstype: iso9660
    - name: Install Guest additions
      become: true
      command: /mnt/VBoxLinuxAdditions.run
    - name: Unmount Guest additions
      become: true
      mount:
        name: /mnt
        src: /home/vagrant/VBoxGuestAdditions.iso
        opts: loop,ro
        state: absent
        fstype: iso9660
    - name: Remove Guest additions
      become: true
      command: rm VBoxGuestAdditions.iso
    - name: Download selenium server
      get_url:
        url: http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar
        dest: /home/vagrant/selenium-standalone-server.jar
    - name: Install selenium standalone service
      copy:
        src: "{{ playbook_dir }}/config/selenium.service"
        dest: /etc/systemd/system/selenium.service
        owner: root
